server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:\Dev\MSA_Dev\native-file-repo
        git:
          uri: https://github.com/Mindecco/spring-cloud-config.git

#          uri: file://D:/Dev/MSA_Dev
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh
