server:
  port: 8761
spring:
  application:
    name: discoveryservice
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-connect-timeout-seconds: 15
  server:
    peer-node-connect-timeout-ms: 10000
